GENERATED_COMPOSE_FILES = stack/production.yml stack/test.yml

compose-files: $(GENERATED_COMPOSE_FILES)

build: .build.sentinel

.build.sentinel: stack/certbot/Dockerfile bin/*.sh stack/development.yml
	docker-compose -f stack/development.yml build
	touch .build.sentinel

stack/%.yml: .env stack/development.yml stack/%.part.yml
	echo '# docker-compose file generated by make' > $@
	docker-compose $(foreach f,$(filter-out .env,$^),-f $f) config >> $@

.env:
	touch $@

.PHONY : clean
clean :
	-rm $(GENERATED_COMPOSE_FILES)
